owner-repo: &owner-repo
  owner-repo: palantir/go-oauth2-client

version: 2.1

orbs:
  go: palantir/go@0.0.13
  godel: palantir/godel@0.0.12

workflows:
  version: 2
  verify-test:
    jobs:
      - godel/verify:
          name: verify
          executor:
            name: go/golang
            version: 1.13.3
            <<: *owner-repo
      - godel/test:
          name: test-go-1.13
          executor:
            name: go/golang
            version: 1.13.3
            <<: *owner-repo
      - godel/test:
          name: test-go-1.12
          executor:
            name: go/golang
            version: 1.12.12
            <<: *owner-repo
